[package]
name = "karga_http"
version = "0.1.0"
edition = "2024"

[dependencies]
hdrhistogram = "7.5.4"
karga = { version = "0.3", features = ["macros"] }
reqwest = "0.12.24"
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1"
typed-builder = "0.23.0"
